/* Generated from game.js by tools/split-game-modules.mjs. Do not edit directly. */
/* state / DOM refs — 마운드 심리전 */
window.MountPsycho = window.MountPsycho || {};
(function (MP) {
MP.state = {
  pitcher: null,
  pitcherChoices: [],
  catcher: null,
  lineup: [],
  batterIndex: 0,
  stageIndex: 0,
  stageThemeId: null,
  awaitingThemeSelection: false,
  pendingThemeChoices: [],
  stageJustAdvanced: false,
  inning: 1,
  outs: 0,
  balls: 0,
  strikes: 0,
  consecutiveBalls: 0,
  bases: [false, false, false],
  runs: 0,
  pitchCount: 0,
  atBat: null,
  selectedPitchId: null,
  pitchIntent: "strike",
  pitchBallPlan: "",
  flashZone: null,
  lastLocation: null,
  lastPitchCall: null,
  consecutiveOnBase: 0,
  fullCountSeen: 0,
  rewardChoices: [],
  rewardPending: false,
  rewardKind: "normal",
  afterRewardStageOverlay: null,
  pendingRewardKindAfterCurrent: null,
  pendingTransitionBanner: null,
  pendingStageOverlay: null,
  coreEvolutionOffered: false,
  pendingCoreEvolutionReward: false,
  selectedRewardIndex: null,
  lastAtBatMemory: null,
  patternMemory: { pitches: [], lastWarningAt: 0 },
  pendingGameOver: false,
  runStats: {
    strikeouts: 0,
    hits: 0,
    doubles: 0,
    homeruns: 0,
    walks: 0,
    doublePlays: 0,
    rewards: 0,
    bossOuts: 0,
    bossDamage: 0
  },
  useCardUiV2: true,
  gameOver: false,
  waitingNextBatter: false,
  batterCardExpanded: false,
  screenPhase: "pitcherSelect"
};

MP.inningBannerTimer = null;
MP.timingTimer = null;
MP.uiEventsBound = false;
MP.autoAdvanceTimer = null;
MP.courseFlashTimer = null;
MP.pitchFlightFrame = null;
MP.rewardTimer = null;
MP.gameOverTimer = null;

MP.els = {
  newGameButton: document.querySelector("#newGameButton"),
  bgmToggle: document.querySelector("#bgmToggle"),
  nextBatterButton: document.querySelector("#nextBatterButton"),
  inningText: document.querySelector("#inningText"),
  runsText: document.querySelector("#runsText"),
  targetText: document.querySelector("#targetText"),
  ballsText: document.querySelector("#ballsText"),
  strikesText: document.querySelector("#strikesText"),
  outsText: document.querySelector("#outsText"),
  base1: document.querySelector("#base1"),
  base2: document.querySelector("#base2"),
  base3: document.querySelector("#base3"),
  pitcherName: document.querySelector("#pitcherName"),
  pitcherPortrait: document.querySelector("#pitcherPortrait"),
  pitcherTags: document.querySelector("#pitcherTags"),
  pitcherTagsStack: document.querySelector(".pitcher-tags-stack"),
  pitcherTagsPark: document.querySelector("#pitcherTagsPark"),
  pitcherTagDetail: document.querySelector("#pitcherTagDetail"),
  pitcherStats: document.querySelector("#pitcherStats"),
  pitcherCardLower: document.querySelector("#pitcherCardLower"),
  pitchArea: document.querySelector(".pitch-area"),
  pitcherCard: document.querySelector(".pitcher-card"),
  pitchButtons: document.querySelector("#pitchButtons"),
  batterName: document.querySelector("#batterName"),
  batterPortrait: document.querySelector("#batterPortrait"),
  battingSlot: document.querySelector("#battingSlot"),
  batterType: document.querySelector("#batterType"),
  tagDetail: document.querySelector("#tagDetail"),
  batterStats: document.querySelector("#batterStats"),
  batterDetailStats: document.querySelector("#batterDetailStats"),
  batterCardLower: document.querySelector("#batterCardLower"),
  batterCard: document.querySelector(".batter-card"),
  batterCardToggle: document.querySelector("#batterCardToggle"),
  suspicionText: document.querySelector("#suspicionText"),
  suspicionFill: document.querySelector("#suspicionFill"),
  suspicionHint: document.querySelector("#suspicionHint"),
  readGuess: document.querySelector("#readGuess"),
  readBars: document.querySelector("#readBars"),
  recommendConfidence: document.querySelector("#recommendConfidence"),
  recommendTitle: document.querySelector("#recommendTitle"),
  recommendText: document.querySelector("#recommendText"),
  catcherTitle: document.querySelector("#catcherTitle"),
  catcherText: document.querySelector("#catcherText"),
  countCardTitle: document.querySelector("#countCardTitle"),
  countCardText: document.querySelector("#countCardText"),
  logList: document.querySelector("#logList"),
  pitchCountText: document.querySelector("#pitchCountText"),
  timingBadge: document.querySelector("#timingBadge"),
  inningBanner: document.querySelector("#inningBanner"),
  batterFigure: document.querySelector("#batterFigure"),
  strikeZone: document.querySelector("#strikeZone"),
  ballSprite: document.querySelector("#ballSprite"),
  resultOverlay: document.querySelector("#resultOverlay"),
  resultTitle: document.querySelector("#resultTitle"),
  resultMessage: document.querySelector("#resultMessage"),
  restartButton: document.querySelector("#restartButton"),
  pitcherSelectOverlay: document.querySelector("#pitcherSelectOverlay"),
  pitcherChoiceList: document.querySelector("#pitcherChoiceList"),
  rewardOverlay: document.querySelector("#rewardOverlay"),
  rewardTitle: document.querySelector("#rewardTitle"),
  rewardReason: document.querySelector("#rewardReason"),
  rewardChoiceList: document.querySelector("#rewardChoiceList"),
  rewardConfirmButton: document.querySelector("#rewardConfirmButton"),
  stageOverlay: document.querySelector("#stageOverlay"),
  stageTitle: document.querySelector("#stageTitle"),
  stageSubtitle: document.querySelector("#stageSubtitle"),
  stageThemePanel: document.querySelector("#stageThemePanel"),
  themeSelectOverlay: document.querySelector("#themeSelectOverlay"),
  themeChoiceList: document.querySelector("#themeChoiceList"),
};

})(window.MountPsycho);
