/* Generated from game.js by tools/split-game-modules.mjs. Do not edit directly. */
/* state / DOM refs — 마운드 심리전 */
window.MountPsycho = window.MountPsycho || {};
(function (MP) {
MP.state = {
  pitcher: null,
  pitcherChoices: [],
  catcher: null,
  lineup: [],
  batterIndex: 0,
  stageIndex: 0,
  stageThemeId: null,
  awaitingThemeSelection: false,
  pendingThemeChoices: [],
  stageJustAdvanced: false,
  awaitingStageStart: false,
  inning: 1,
  outs: 0,
  balls: 0,
  strikes: 0,
  consecutiveBalls: 0,
  bases: [false, false, false],
  runs: 0,
  pitchCount: 0,
  atBat: null,
  selectedPitchId: null,
  pitchIntent: "strike",
  pitchBallPlan: "",
  releaseTiming: null,
  lastReleaseResult: null,
  flashZone: null,
  lastLocation: null,
  lastPitchCall: null,
  consecutiveOnBase: 0,
  fullCountSeen: 0,
  rewardChoices: [],
  rewardPending: false,
  rewardKind: "normal",
  afterRewardStageOverlay: null,
  pendingRewardKindAfterCurrent: null,
  pendingTransitionBanner: null,
  pendingStageOverlay: null,
  coreEvolutionOffered: false,
  pendingCoreEvolutionReward: false,
  lastAtBatMemory: null,
  ownedRewardCards: [],
  cardTriggerLog: [],
  stageRun: null,
  currentInningStats: null,
  currentAtBatMeta: null,
  pendingDugoutChoices: [],
  dugoutPending: false,
  dugoutBeforeAtBat: false,
  dugoutAdvanceBatterOnConfirm: false,
  activeDugoutEffects: [],
  pendingRunComplete: false,
  pendingRunCompleteMessage: "",
  lastStageResult: null,
  nextBatterSuspicionBonus: 0,
  nextPitchControlBonus: 0,
  patternMemory: { pitches: [], lastWarningAt: 0 },
  pendingGameOver: false,
  tutorialSeen: {},
  runStats: {
    strikeouts: 0,
    hits: 0,
    doubles: 0,
    homeruns: 0,
    walks: 0,
    doublePlays: 0,
    rewards: 0,
    bossOuts: 0,
    bossDamage: 0
  },
  useCardUiV2: true,
  gameOver: false,
  waitingNextBatter: false,
  batterCardExpanded: false,
  screenPhase: "title"
};

MP.inningBannerTimer = null;
MP.timingTimer = null;
MP.uiEventsBound = false;
MP.autoAdvanceTimer = null;
MP.courseFlashTimer = null;
MP.pitchFlightFrame = null;
MP.releaseTimingFrame = null;
MP.rewardTimer = null;
MP.inningBannerDismissHandler = null;
MP.timingDismissHandler = null;
MP.rewardRevealTimer = null;
MP.dugoutRevealTimer = null;
MP.pitcherRevealTimer = null;
MP.gameOverTimer = null;

MP.els = {
  newGameButton: document.querySelector("#newGameButton"),
  bgmToggle: document.querySelector("#bgmToggle"),
  nextBatterButton: document.querySelector("#nextBatterButton"),
  inningText: document.querySelector("#inningText"),
  runsText: document.querySelector("#runsText"),
  targetText: document.querySelector("#targetText"),
  ballsText: document.querySelector("#ballsText"),
  strikesText: document.querySelector("#strikesText"),
  outsText: document.querySelector("#outsText"),
  base1: document.querySelector("#base1"),
  base2: document.querySelector("#base2"),
  base3: document.querySelector("#base3"),
  pitcherName: document.querySelector("#pitcherName"),
  pitcherPortrait: document.querySelector("#pitcherPortrait"),
  pitcherTags: document.querySelector("#pitcherTags"),
  pitcherTagsStack: document.querySelector(".pitcher-tags-stack"),
  pitcherTagsPark: document.querySelector("#pitcherTagsPark"),
  pitcherTagDetail: document.querySelector("#pitcherTagDetail"),
  pitcherStats: document.querySelector("#pitcherStats"),
  pitcherCardLower: document.querySelector("#pitcherCardLower"),
  pitchArea: document.querySelector(".pitch-area"),
  pitcherCard: document.querySelector(".pitcher-card"),
  pitchButtons: document.querySelector("#pitchButtons"),
  batterName: document.querySelector("#batterName"),
  batterPortrait: document.querySelector("#batterPortrait"),
  battingSlot: document.querySelector("#battingSlot"),
  batterType: document.querySelector("#batterType"),
  tagDetail: document.querySelector("#tagDetail"),
  batterStats: document.querySelector("#batterStats"),
  batterDetailStats: document.querySelector("#batterDetailStats"),
  batterCardLower: document.querySelector("#batterCardLower"),
  batterCard: document.querySelector(".batter-card"),
  batterCardToggle: document.querySelector("#batterCardToggle"),
  suspicionText: document.querySelector("#suspicionText"),
  suspicionFill: document.querySelector("#suspicionFill"),
  suspicionHint: document.querySelector("#suspicionHint"),
  readGuess: document.querySelector("#readGuess"),
  readBars: document.querySelector("#readBars"),
  recommendConfidence: document.querySelector("#recommendConfidence"),
  recommendTitle: document.querySelector("#recommendTitle"),
  recommendText: document.querySelector("#recommendText"),
  catcherTitle: document.querySelector("#catcherTitle"),
  catcherText: document.querySelector("#catcherText"),
  releaseTimingPanel: document.querySelector("#releaseTimingPanel"),
  releaseTimingButton: document.querySelector("#releaseTimingButton"),
  releaseTimingGrade: document.querySelector("#releaseTimingGrade"),
  releaseTimingMode: document.querySelector("#releaseTimingMode"),
  releaseTimingTrack: document.querySelector("#releaseTimingTrack"),
  releaseGoodZone: document.querySelector("#releaseGoodZone"),
  releasePerfectZone: document.querySelector("#releasePerfectZone"),
  releaseTimingCursor: document.querySelector("#releaseTimingCursor"),
  releaseTimingHint: document.querySelector("#releaseTimingHint"),
  logList: document.querySelector("#logList"),
  pitchCountText: document.querySelector("#pitchCountText"),
  timingBadge: document.querySelector("#timingBadge"),
  inningBanner: document.querySelector("#inningBanner"),
  batterFigure: document.querySelector("#batterFigure"),
  strikeZone: document.querySelector("#strikeZone"),
  ballSprite: document.querySelector("#ballSprite"),
  resultOverlay: document.querySelector("#resultOverlay"),
  resultTitle: document.querySelector("#resultTitle"),
  resultMessage: document.querySelector("#resultMessage"),
  restartButton: document.querySelector("#restartButton"),
  titleOverlay: document.querySelector("#titleOverlay"),
  titleStartButton: document.querySelector("#titleStartButton"),
  titleTutorialButton: document.querySelector("#titleTutorialButton"),
  tutorialOverlay: document.querySelector("#tutorialOverlay"),
  tutorialBackButton: document.querySelector("#tutorialBackButton"),
  pitcherSelectOverlay: document.querySelector("#pitcherSelectOverlay"),
  pitcherChoiceList: document.querySelector("#pitcherChoiceList"),
  rewardOverlay: document.querySelector("#rewardOverlay"),
  rewardTitle: document.querySelector("#rewardTitle"),
  rewardReason: document.querySelector("#rewardReason"),
  rewardChoiceList: document.querySelector("#rewardChoiceList"),
  stageOverlay: document.querySelector("#stageOverlay"),
  stageTitle: document.querySelector("#stageTitle"),
  stageSubtitle: document.querySelector("#stageSubtitle"),
  stageThemePanel: document.querySelector("#stageThemePanel"),
  stageStartButton: document.querySelector("#stageStartButton"),
  stageThemeBadge: document.querySelector("#stageThemeBadge"),
  themeSelectOverlay: document.querySelector("#themeSelectOverlay"),
  themeChoiceList: document.querySelector("#themeChoiceList"),
  stageThemeDetailOverlay: document.querySelector("#stageThemeDetailOverlay"),
  stageThemeDetailTitle: document.querySelector("#stageThemeDetailTitle"),
  stageThemeDetailBody: document.querySelector("#stageThemeDetailBody"),
  stageThemeDetailClose: document.querySelector("#stageThemeDetailClose"),
  missionFocusCard: document.querySelector("#missionFocusCard"),
  missionFocusTitle: document.querySelector("#missionFocusTitle"),
  missionFocusStatus: document.querySelector("#missionFocusStatus"),
  missionFocusCondition: document.querySelector("#missionFocusCondition"),
  missionFocusReward: document.querySelector("#missionFocusReward"),
  missionFocusRewardRow: document.querySelector("#missionFocusRewardRow"),
  runStatusCard: document.querySelector("#runStatusCard"),
  runStageName: document.querySelector("#runStageName"),
  runMissionText: document.querySelector("#runMissionText"),
  runRivalText: document.querySelector("#runRivalText"),
  runStarText: document.querySelector("#runStarText"),
  ownedCardSummary: document.querySelector("#ownedCardSummary"),
  cardTriggerLog: document.querySelector("#cardTriggerLog"),
  dugoutOverlay: document.querySelector("#dugoutOverlay"),
  dugoutChoiceList: document.querySelector("#dugoutChoiceList"),
  dugoutTitle: document.querySelector("#dugoutTitle"),
  dugoutReason: document.querySelector("#dugoutReason"),
  mobileBatterToggle: document.querySelector("#mobileBatterToggle"),
  mobileLogMore: document.querySelector("#mobileLogMore"),
  mobilePitchTab: document.querySelector("#mobilePitchTab"),
  mobileLogTab: document.querySelector("#mobileLogTab"),
  mobileInfoTab: document.querySelector("#mobileInfoTab"),
  mobileGameShell: document.querySelector("#mobileGameShell"),
  mobileStageThemeSummary: document.querySelector("#mobileStageThemeSummary"),
  mobileNewGameButton: document.querySelector("#mobileNewGameButton"),
  mobileInningText: document.querySelector("#mobileInningText"),
  mobileRunsText: document.querySelector("#mobileRunsText"),
  mobileTargetText: document.querySelector("#mobileTargetText"),
  mobileBallsDots: document.querySelector("#mobileBallsDots"),
  mobileStrikesDots: document.querySelector("#mobileStrikesDots"),
  mobileOutsDots: document.querySelector("#mobileOutsDots"),
  mobileBases: document.querySelector("#mobileBases"),
  mobileMissionCard: document.querySelector("#mobileMissionCard"),
  mobileMissionTitle: document.querySelector("#mobileMissionTitle"),
  mobileMissionCondition: document.querySelector("#mobileMissionCondition"),
  mobileMissionStatus: document.querySelector("#mobileMissionStatus"),
  mobilePitcherName: document.querySelector("#mobilePitcherName"),
  mobilePitcherTags: document.querySelector("#mobilePitcherTags"),
  mobileBatterName: document.querySelector("#mobileBatterName"),
  mobileBatterTags: document.querySelector("#mobileBatterTags"),
  mobilePlayerDetailPanel: document.querySelector("#mobilePlayerDetailPanel"),
  mobileBattingSlot: document.querySelector("#mobileBattingSlot"),
  mobileSuspicionFill: document.querySelector("#mobileSuspicionFill"),
  mobileSuspicionText: document.querySelector("#mobileSuspicionText"),
  mobileStrikeZone: document.querySelector("#mobileStrikeZone"),
  mobileInningBanner: document.querySelector("#mobileInningBanner"),
  mobileTimingBadge: document.querySelector("#mobileTimingBadge"),
  mobileBallSprite: document.querySelector("#mobileBallSprite"),
  mobilePitchButtons: document.querySelector("#mobilePitchButtons"),
  mobileReleasePanel: document.querySelector("#mobileReleasePanel"),
  mobileReleaseGrade: document.querySelector("#mobileReleaseGrade"),
  mobileReleaseMode: document.querySelector("#mobileReleaseMode"),
  mobileReleaseCursor: document.querySelector("#mobileReleaseCursor"),
  mobileRecommendConfidence: document.querySelector("#mobileRecommendConfidence"),
  mobileRecommendTitle: document.querySelector("#mobileRecommendTitle"),
  mobileRecommendText: document.querySelector("#mobileRecommendText"),
  mobileDuelReadFlow: document.querySelector("#mobileDuelReadFlow"),
  mobileDuelReadPitch: document.querySelector("#mobileDuelReadPitch"),
  mobileDuelReadRisk: document.querySelector("#mobileDuelReadRisk"),
  mobileRecentLog: document.querySelector("#mobileRecentLog"),
  mobileRecentLogMore: document.querySelector("#mobileRecentLogMore"),
  mobileThrowButton: document.querySelector("#mobileThrowButton"),
  mobilePanelBackdrop: document.querySelector("#mobilePanelBackdrop"),
  mobileInfoPanel: document.querySelector("#mobileInfoPanel"),
  mobileInfoPanelTitle: document.querySelector("#mobileInfoPanelTitle"),
  mobileInfoPanelBody: document.querySelector("#mobileInfoPanelBody"),
  mobileInfoPanelClose: document.querySelector("#mobileInfoPanelClose"),
  mobileSheetBackdrop: document.querySelector("#mobileSheetBackdrop"),
};

})(window.MountPsycho);
